/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.GUI;

/**
 *
 * @author matba
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblLeftGrid = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel66 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1416, 939));

        jPanel1.setBackground(new java.awt.Color(0, 40, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielveza.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 700, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bieljazdec.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielstrelec.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielkral.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielkralovna.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielstrelec.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bieljazdec.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielveza.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernveza.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 100, 100));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernjazdec.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 100));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernstrelec.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 100, 100));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernkralovna.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 100));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernkral.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 100, 100));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernstrelec.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, 100));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernjazdec.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 100));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 100, 100));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernveza.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 100, 100));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 100, 100));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 100));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, 100));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 100));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 100));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 100));

        lblBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/chess_board.png"))); // NOI18N
        jPanel2.add(lblBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(237, 223, 206));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel3.setPreferredSize(new java.awt.Dimension(40, 340));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/ciernpesiak.png"))); // NOI18N
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, 340));

        jPanel4.setBackground(new java.awt.Color(148, 51, 13));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel4.setPreferredSize(new java.awt.Dimension(40, 340));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/20x20/bieljazdec.png"))); // NOI18N
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, -1, 340));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(40, 780));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLeftGrid.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLeftGrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeftGrid.setText("<html>8<br><br>7<br><br>6<br><br>5<br><br>4<br><br>3<br><br>2<br><br>1</html>");
        jPanel5.add(lblLeftGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 780));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(780, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("A      B      C      D      E      F      G      H");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 780, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 840, -1, -1));

        jPanel7.setBackground(new java.awt.Color(237, 223, 206));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setText("A2->A4\n----------\nA7->A5\n----------\nD2->D4\n----------\nD7->D4\n----------\n\n\n\n\n\n\n\n\n\n\n\n\n\n---------");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 400, 280));

        jLabel66.setText("Move history:");
        jPanel7.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setBackground(new java.awt.Color(255, 255, 0));
        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel67.setText("Matko Kubko, 192.168.78.55");
        jPanel8.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 420, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblLeftGrid;
    // End of variables declaration//GEN-END:variables
}
