/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.GUI;

import java.awt.Image;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author matba
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        panelGameBoard.setLayout(null);
    }

    private int[] nextPosBlackElim = {810, 70};
    private int[] nextPosWhiteElim = {810, 710};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelGame = new javax.swing.JPanel();
        panelGameBoard = new javax.swing.JPanel();
        whitePawnA = new javax.swing.JLabel();
        whitePawnB = new javax.swing.JLabel();
        whitePawnC = new javax.swing.JLabel();
        whitePawnD = new javax.swing.JLabel();
        whitePawnE = new javax.swing.JLabel();
        whitePawnF = new javax.swing.JLabel();
        whitePawnG = new javax.swing.JLabel();
        whitePawnH = new javax.swing.JLabel();
        whiteRookL = new javax.swing.JLabel();
        whiteKnightL = new javax.swing.JLabel();
        whiteBishopL = new javax.swing.JLabel();
        whiteQueen = new javax.swing.JLabel();
        whiteKing = new javax.swing.JLabel();
        whiteBishopR = new javax.swing.JLabel();
        whiteKnightR = new javax.swing.JLabel();
        whiteRookR = new javax.swing.JLabel();
        blackPawnA = new javax.swing.JLabel();
        blackPawnB = new javax.swing.JLabel();
        blackPawnC = new javax.swing.JLabel();
        blackPawnD = new javax.swing.JLabel();
        blackPawnE = new javax.swing.JLabel();
        blackPawnF = new javax.swing.JLabel();
        blackPawnG = new javax.swing.JLabel();
        blackPawnH = new javax.swing.JLabel();
        blackRookL = new javax.swing.JLabel();
        blackKnightL = new javax.swing.JLabel();
        blackBishopL = new javax.swing.JLabel();
        blackQueen = new javax.swing.JLabel();
        blackKing = new javax.swing.JLabel();
        blackBishopR = new javax.swing.JLabel();
        blackKnightR = new javax.swing.JLabel();
        blackRookR = new javax.swing.JLabel();
        lblGameBoard = new javax.swing.JLabel();
        panelGameWhiteMiniFigures = new javax.swing.JPanel();
        panelGameBlackMiniFigures = new javax.swing.JPanel();
        panelGameRows = new javax.swing.JPanel();
        lblGameRows = new javax.swing.JLabel();
        panelGameColumns = new javax.swing.JPanel();
        txtGameColumns = new javax.swing.JLabel();
        panelGameDialog = new javax.swing.JPanel();
        scrollGameMoveHistory = new javax.swing.JScrollPane();
        txtGameMoveHistory = new javax.swing.JTextPane();
        lblGameMoveHistory = new javax.swing.JLabel();
        comboGameBoardColor = new javax.swing.JComboBox<>();
        lblGameBoardColor = new javax.swing.JLabel();
        panelGamePlayerTimer = new javax.swing.JPanel();
        lblGamePlayerTimer = new javax.swing.JLabel();
        panelGameOpponentTimer = new javax.swing.JPanel();
        lblGameOpponentTimer = new javax.swing.JLabel();
        panelGameOpponentInfo = new javax.swing.JPanel();
        lblGameOpponentInfo = new javax.swing.JLabel();
        panelInit = new javax.swing.JPanel();
        panelInitTitle = new javax.swing.JPanel();
        lblInitGameShortcut = new javax.swing.JLabel();
        lblInitGameName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OMGOC - OnlineMultiplayerGameOfChess");
        setPreferredSize(new java.awt.Dimension(1416, 939));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1400, 900));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGame.setBackground(new java.awt.Color(0, 40, 60));
        panelGame.setPreferredSize(new java.awt.Dimension(1400, 900));
        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGameBoard.setBackground(new java.awt.Color(255, 255, 255));
        panelGameBoard.setOpaque(false);
        panelGameBoard.setPreferredSize(new java.awt.Dimension(800, 800));
        panelGameBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whitePawnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        whitePawnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        whitePawnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, -1, -1));

        whitePawnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, -1));

        whitePawnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        whitePawnF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, -1, -1));

        whitePawnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));

        whitePawnH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielpesiak.png"))); // NOI18N
        panelGameBoard.add(whitePawnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 100, 100));

        whiteRookL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielveza.png"))); // NOI18N
        panelGameBoard.add(whiteRookL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, -1));

        whiteKnightL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bieljazdec.png"))); // NOI18N
        panelGameBoard.add(whiteKnightL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, -1));

        whiteBishopL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielstrelec.png"))); // NOI18N
        panelGameBoard.add(whiteBishopL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, -1, -1));

        whiteQueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielkralovna.png"))); // NOI18N
        panelGameBoard.add(whiteQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, -1, -1));

        whiteKing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielkral.png"))); // NOI18N
        panelGameBoard.add(whiteKing, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, -1));

        whiteBishopR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielstrelec.png"))); // NOI18N
        panelGameBoard.add(whiteBishopR, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, -1, -1));

        whiteKnightR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bieljazdec.png"))); // NOI18N
        panelGameBoard.add(whiteKnightR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, -1, -1));

        whiteRookR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/bielveza.png"))); // NOI18N
        panelGameBoard.add(whiteRookR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 700, -1, -1));

        blackPawnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 100));

        blackPawnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 100));

        blackPawnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 100));

        blackPawnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, 100));

        blackPawnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 100));

        blackPawnF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 100, 100));

        blackPawnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 100, 100));

        blackPawnH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernpesiak.png"))); // NOI18N
        panelGameBoard.add(blackPawnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 100, 100));

        blackRookL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernveza.png"))); // NOI18N
        panelGameBoard.add(blackRookL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        blackKnightL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernjazdec.png"))); // NOI18N
        panelGameBoard.add(blackKnightL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 100));

        blackBishopL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernstrelec.png"))); // NOI18N
        panelGameBoard.add(blackBishopL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, 100));

        blackQueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernkralovna.png"))); // NOI18N
        panelGameBoard.add(blackQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 100));

        blackKing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernkral.png"))); // NOI18N
        panelGameBoard.add(blackKing, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 100, 100));

        blackBishopR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernstrelec.png"))); // NOI18N
        panelGameBoard.add(blackBishopR, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 100, 100));

        blackKnightR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernjazdec.png"))); // NOI18N
        panelGameBoard.add(blackKnightR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 100));

        blackRookR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/100x100/ciernveza.png"))); // NOI18N
        panelGameBoard.add(blackRookR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 100, 100));

        lblGameBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figurky_png/boards/woodboard.png"))); // NOI18N
        lblGameBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblGameBoardMouseReleased(evt);
            }
        });
        panelGameBoard.add(lblGameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelGameWhiteMiniFigures.setBackground(new java.awt.Color(237, 223, 206));
        panelGameWhiteMiniFigures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        panelGameWhiteMiniFigures.setPreferredSize(new java.awt.Dimension(40, 340));
        panelGameWhiteMiniFigures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGameBoard.add(panelGameWhiteMiniFigures, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, 340));

        panelGameBlackMiniFigures.setBackground(new java.awt.Color(148, 51, 13));
        panelGameBlackMiniFigures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        panelGameBlackMiniFigures.setPreferredSize(new java.awt.Dimension(40, 340));
        panelGameBlackMiniFigures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGameBoard.add(panelGameBlackMiniFigures, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, 340));

        panelGame.add(panelGameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 840, 800));

        panelGameRows.setBackground(new java.awt.Color(255, 255, 255));
        panelGameRows.setPreferredSize(new java.awt.Dimension(40, 780));
        panelGameRows.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGameRows.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblGameRows.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGameRows.setText("<html>8<br><br><br><br>7<br><br><br><br>6<br><br><br><br>5<br><br><br><br>4<br><br><br><br>3<br><br><br><br>2<br><br><br><br>1</html>");
        panelGameRows.add(lblGameRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 780));

        panelGame.add(panelGameRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        panelGameColumns.setBackground(new java.awt.Color(255, 255, 255));
        panelGameColumns.setPreferredSize(new java.awt.Dimension(780, 40));
        panelGameColumns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGameColumns.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtGameColumns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGameColumns.setText("A              B              C              D              E              F              G              H");
        panelGameColumns.add(txtGameColumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 780, 40));

        panelGame.add(panelGameColumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 840, -1, -1));

        panelGameDialog.setBackground(new java.awt.Color(237, 223, 206));
        panelGameDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGameMoveHistory.setText("A2->A4\n----------\nA7->A5\n----------\nD2->D4\n----------\nD7->D4\n----------\n\n\n\n\n\n\n\n\n\n\n\n\n\n---------");
        txtGameMoveHistory.setFocusable(false);
        scrollGameMoveHistory.setViewportView(txtGameMoveHistory);

        panelGameDialog.add(scrollGameMoveHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 410, 210));

        lblGameMoveHistory.setText("Move history:");
        panelGameDialog.add(lblGameMoveHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        comboGameBoardColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Blue", "Brown", "Green", "Grey", "Red" }));
        comboGameBoardColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGameBoardColorItemStateChanged(evt);
            }
        });
        panelGameDialog.add(comboGameBoardColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, 30));

        lblGameBoardColor.setText("Customize board");
        panelGameDialog.add(lblGameBoardColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelGame.add(panelGameDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 420, 470));

        panelGamePlayerTimer.setBackground(new java.awt.Color(200, 200, 200));
        panelGamePlayerTimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGamePlayerTimer.setText("Hodiny super");
        panelGamePlayerTimer.add(lblGamePlayerTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 60));

        panelGame.add(panelGamePlayerTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 720, 420, 70));

        panelGameOpponentTimer.setBackground(new java.awt.Color(200, 200, 200));
        panelGameOpponentTimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGameOpponentTimer.setText("Hodiny super");
        panelGameOpponentTimer.add(lblGameOpponentTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, 60));

        panelGame.add(panelGameOpponentTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 420, 70));

        panelGameOpponentInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelGameOpponentInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGameOpponentInfo.setBackground(new java.awt.Color(255, 255, 0));
        lblGameOpponentInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGameOpponentInfo.setText("Matko Kubko, 192.168.78.55");
        panelGameOpponentInfo.add(lblGameOpponentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 20));

        panelGame.add(panelGameOpponentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 290, 40));

        jLayeredPane1.add(panelGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelInit.setBackground(new java.awt.Color(0, 40, 60));
        panelInit.setPreferredSize(new java.awt.Dimension(1400, 900));
        panelInit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInitTitle.setBackground(new java.awt.Color(255, 255, 255));
        panelInitTitle.setPreferredSize(new java.awt.Dimension(600, 250));
        panelInitTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInitGameShortcut.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        lblInitGameShortcut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInitGameShortcut.setText("OMGOC");
        panelInitTitle.add(lblInitGameShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 460, -1));

        lblInitGameName.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        lblInitGameName.setForeground(new java.awt.Color(0, 40, 160));
        lblInitGameName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInitGameName.setText("Online Multiplayer Game Of Chess");
        panelInitTitle.add(lblInitGameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 570, -1));

        panelInit.add(panelInitTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLayeredPane1.add(panelInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblGameBoardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGameBoardMouseReleased
        // TODO add your handling code here:
        eliminateFigure(whiteQueen, true);
        eliminateFigure(blackPawnB, false);
    }//GEN-LAST:event_lblGameBoardMouseReleased

    private void comboGameBoardColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGameBoardColorItemStateChanged
        // TODO add your handling code here:
        String color = comboGameBoardColor.getSelectedItem().toString();
        if (color == null) {
            return;
        }
        switch (color) {
            case "Default":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "woodboard.png").toString()));
                break;
            case "Blue":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "blueboard.png").toString()));
                break;
            case "Brown":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "brownboard.png").toString()));
                break;
            case "Green":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "greenboard.png").toString()));
                break;
            case "Grey":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "greyboard.png").toString()));
                break;
            case "Red":
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "redboard.png").toString()));
                break;
            default:
                lblGameBoard.setIcon(new ImageIcon(Paths.get("src", "figurky_png", "boards", "woodboard.png").toString()));
        }
    }//GEN-LAST:event_comboGameBoardColorItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blackBishopL;
    private javax.swing.JLabel blackBishopR;
    private javax.swing.JLabel blackKing;
    private javax.swing.JLabel blackKnightL;
    private javax.swing.JLabel blackKnightR;
    private javax.swing.JLabel blackPawnA;
    private javax.swing.JLabel blackPawnB;
    private javax.swing.JLabel blackPawnC;
    private javax.swing.JLabel blackPawnD;
    private javax.swing.JLabel blackPawnE;
    private javax.swing.JLabel blackPawnF;
    private javax.swing.JLabel blackPawnG;
    private javax.swing.JLabel blackPawnH;
    private javax.swing.JLabel blackQueen;
    private javax.swing.JLabel blackRookL;
    private javax.swing.JLabel blackRookR;
    private javax.swing.JComboBox<String> comboGameBoardColor;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblGameBoard;
    private javax.swing.JLabel lblGameBoardColor;
    private javax.swing.JLabel lblGameMoveHistory;
    private javax.swing.JLabel lblGameOpponentInfo;
    private javax.swing.JLabel lblGameOpponentTimer;
    private javax.swing.JLabel lblGamePlayerTimer;
    private javax.swing.JLabel lblGameRows;
    private javax.swing.JLabel lblInitGameName;
    private javax.swing.JLabel lblInitGameShortcut;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelGameBlackMiniFigures;
    private javax.swing.JPanel panelGameBoard;
    private javax.swing.JPanel panelGameColumns;
    private javax.swing.JPanel panelGameDialog;
    private javax.swing.JPanel panelGameOpponentInfo;
    private javax.swing.JPanel panelGameOpponentTimer;
    private javax.swing.JPanel panelGamePlayerTimer;
    private javax.swing.JPanel panelGameRows;
    private javax.swing.JPanel panelGameWhiteMiniFigures;
    private javax.swing.JPanel panelInit;
    private javax.swing.JPanel panelInitTitle;
    private javax.swing.JScrollPane scrollGameMoveHistory;
    private javax.swing.JLabel txtGameColumns;
    private javax.swing.JTextPane txtGameMoveHistory;
    private javax.swing.JLabel whiteBishopL;
    private javax.swing.JLabel whiteBishopR;
    private javax.swing.JLabel whiteKing;
    private javax.swing.JLabel whiteKnightL;
    private javax.swing.JLabel whiteKnightR;
    private javax.swing.JLabel whitePawnA;
    private javax.swing.JLabel whitePawnB;
    private javax.swing.JLabel whitePawnC;
    private javax.swing.JLabel whitePawnD;
    private javax.swing.JLabel whitePawnE;
    private javax.swing.JLabel whitePawnF;
    private javax.swing.JLabel whitePawnG;
    private javax.swing.JLabel whitePawnH;
    private javax.swing.JLabel whiteQueen;
    private javax.swing.JLabel whiteRookL;
    private javax.swing.JLabel whiteRookR;
    // End of variables declaration//GEN-END:variables

    private void resetElimPosValues() {
        nextPosBlackElim[0] = 810;
        nextPosBlackElim[1] = 70;
        nextPosWhiteElim[0] = 810;
        nextPosWhiteElim[1] = 710;
    }

    private void eliminateFigure(JLabel figure, boolean isWhite) {
        figure.setIcon(rescale((ImageIcon) figure.getIcon(), 20, 20));
        if (isWhite) {
            figure.setBounds(nextPosWhiteElim[0], nextPosWhiteElim[1], 20, 20);
            nextPosWhiteElim[1] -= 20;
        } else {
            figure.setBounds(nextPosBlackElim[0], nextPosBlackElim[1], 20, 20);
            nextPosBlackElim[1] += 20;
        }
    }

    private ImageIcon rescale(ImageIcon i, int width, int height) {
        Image image = i.getImage();
        Image newImage = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newImage);
    }
}
